"""empty message

Revision ID: 136881012499
Revises: ab640d683187
Create Date: 2020-05-02 17:01:28.264035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '136881012499'
down_revision = 'ab640d683187'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('artists', sa.Column('seeking_talent_desc', sa.String(length=120), nullable=True))
    op.add_column('venues', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('venues', sa.Column('seeking_talent_desc', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'seeking_talent_desc')
    op.drop_column('venues', 'seeking_talent')
    op.drop_column('artists', 'seeking_talent_desc')
    op.drop_column('artists', 'seeking_talent')
    # ### end Alembic commands ###
