"""empty message

Revision ID: d1eab16c72de
Revises: 136881012499
Create Date: 2020-05-02 20:13:27.635310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1eab16c72de'
down_revision = '136881012499'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.add_column('artists', sa.Column('seeking_venue_desc', sa.String(length=120), nullable=True))
    op.drop_column('artists', 'seeking_talent_desc')
    op.drop_column('artists', 'seeking_talent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('seeking_talent', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('artists', sa.Column('seeking_talent_desc', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('artists', 'seeking_venue_desc')
    op.drop_column('artists', 'seeking_venue')
    # ### end Alembic commands ###
